[package]
name = "webrender_bindings"
version = "0.1.0"
authors = ["The Mozilla Project Developers"]
license = "MPL-2.0"

[features]
webrender_debugger = ["webrender/debugger"]

[dependencies]
rayon = "1"
num_cpus = "1.7.0"
thread_profiler = "0.1.1"
<<<<<<< HEAD
euclid = { version = "0.19.3", features = ["serde"] }
||||||| merged common ancestors
euclid = { version = "0.19", features = ["serde"] }
=======
euclid = { version = "0.19.4", features = ["serde"] }
>>>>>>> upstream-releases
app_units = "0.7"
<<<<<<< HEAD
gleam = "0.6.8"
||||||| merged common ancestors
gleam = "0.6.3"
=======
gleam = "0.6.14"
>>>>>>> upstream-releases
log = "0.4"
nsstring = { path = "../../xpcom/rust/nsstring" }
bincode = "1.0"
uuid = { version = "0.6", features = ["v4"] }
fxhash = "0.2.1"

[dependencies.webrender]
<<<<<<< HEAD
path = "../wr/webrender"
version = "0.57.2"
||||||| merged common ancestors
path = "../webrender"
version = "0.57.2"
=======
path = "../wr/webrender"
version = "0.60.0"
>>>>>>> upstream-releases
default-features = false
features = ["capture", "serialize_program"]

[target.'cfg(target_os = "windows")'.dependencies]
<<<<<<< HEAD
dwrote = "0.6.2"
||||||| merged common ancestors
dwrote = "0.5.2"
=======
dwrote = "0.9"
>>>>>>> upstream-releases

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.6"
core-graphics = "0.17.1"
foreign-types = "0.3.0"

