[package]
name = "mozurl"
version = "0.0.1"
authors = ["Nika Layzell <nika@thelayzells.com>"]

[dependencies]
<<<<<<< HEAD
url = "1.7.2"
nsstring = { path = "../../../servo/support/gecko/nsstring" }
||||||| merged common ancestors
url = "1.5.1"
nsstring = { path = "../../../servo/support/gecko/nsstring" }
=======
url = "1.7.2"
>>>>>>> upstream-releases
nserror = { path = "../../../xpcom/rust/nserror" }
nsstring = { path = "../../../xpcom/rust/nsstring" }
xpcom = { path = "../../../xpcom/rust/xpcom" }
uuid = { version = "0.7.2", features = ["v4"] }
