[package]
name = "webrender_api"
version = "0.60.0"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]
license = "MPL-2.0"
repository = "https://github.com/servo/webrender"
description = "Public API for WebRender"
edition = "2018"

[features]
nightly = ["euclid/unstable", "serde/unstable"]
ipc = ["ipc-channel"]
serialize = []
deserialize = []
display_list_stats = []

[dependencies]
app_units = "0.7"
bincode = "1.0"
bitflags = "1.0"
byteorder = "1.2.1"
derive_more = "0.13"
ipc-channel = {version = "0.11.0", optional = true}
<<<<<<< HEAD:mozilla-release/gfx/wr/webrender_api/Cargo.toml
euclid = { version = "0.19.3", features = ["serde"] }
serde = { version = "=1.0.80", features = ["rc"] }
serde_derive = { version = "=1.0.80", features = ["deserialize_in_place"] }
||||||| merged common ancestors
euclid = { version = "0.19", features = ["serde"] }
serde = { version = "=1.0.66", features = ["rc"] }
serde_derive = { version = "=1.0.66", features = ["deserialize_in_place"] }
=======
euclid = { version = "0.19.5", features = ["serde"] }
malloc_size_of_derive = "0.1"
serde = { version = "=1.0.88", features = ["rc"] }
serde_derive = { version = "=1.0.88", features = ["deserialize_in_place"] }
>>>>>>> upstream-releases:mozilla-release/gfx/wr/webrender_api/Cargo.toml
serde_bytes = "0.10"
time = "0.1"
malloc_size_of = { version = "0.0.1", path = "../wr_malloc_size_of", package = "wr_malloc_size_of" }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.6"
core-graphics = "0.17.1"
<<<<<<< HEAD:mozilla-release/gfx/wr/webrender_api/Cargo.toml

[target.'cfg(target_os = "windows")'.dependencies]
dwrote = "0.6.2"
||||||| merged common ancestors

[target.'cfg(target_os = "windows")'.dependencies]
dwrote = "0.5.2"
=======
>>>>>>> upstream-releases:mozilla-release/gfx/wr/webrender_api/Cargo.toml
